# -*- coding: utf-8 -*-
"""review_summarizer_ai.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q06ilwK-Ic9d_2L1vBj0H6l66c8kRzVy

**data**
"""

reviews_main = [
    "The product quality is excellent and worth the price",
    "Delivery was very late and disappointing",
    "Packaging was damaged but product works fine",
    "Affordable and useful for daily use",
    "Customer service is very slow",
    "Design is beautiful and performance is great",
    "Not worth the money",
    "Value for money product",
    "Battery life is too short",
    "Very satisfied with the purchase"
]

"""**Requried Libraries**"""

!pip install groq
from groq import Groq
import json
from google.colab import userdata
import os

"""**Setup Envirnonment**"""

os.environ["GROQ_API_KEY"] = userdata.get('Groq_class')
client = Groq(api_key=os.environ["GROQ_API_KEY"])

"""**LLM 'llama' model Building**"""

def analyze_reviews(reviews):
    reviews_text = "\n".join(reviews)
    prompt = f""" You are an AI assistant that analyzes product reviews.

              Return output in STRICT JSON format:
              {{
                "summary": "Write a short, natural 1-sentence summary without phrases like 'the product received a review".
                "pros": [],
                "cons": [],
                "sentiment": "Positive/Negative/Mixed/Neutral",
                "confidence": 0.0
              }}

              Rules:
              - Output MUST be valid JSON
              - Confidence should be between 0 and 1
              - If unsure, reduce confidence
              - If reviews are unclear, return Neutral with low confidence
              - Correct minor spelling mistakes in output
              - Only use given reviews
              - Be concise

              Reviews:
              {reviews_text}
              """

    response = client.chat.completions.create(model="llama-3.1-8b-instant",
                                              messages=[{"role": "user", "content": prompt}],
                                              temperature=0.3)

    return response.choices[0].message.content

# Safe JSON parsing
def safe_parse(output):
    try:
        return json.loads(output)
    except Exception as e:
        print("JSON parsing failed:", e)
        return None

# Validation function
def validate_output(data):

    if data is None:
        print("No data to validate")
        return False

    required_keys = ["summary", "pros", "cons", "sentiment", "confidence"]

    for key in required_keys:
        if key not in data:
            print(f"{key} missing")
            return False

    if not isinstance(data["pros"], list):
        print("pros should be list")
        return False

    if not isinstance(data["cons"], list):
        print("cons should be list")
        return False

    if data["sentiment"] not in ["Positive", "Negative", "Mixed", "Neutral"]:
        print("invalid sentiment value")
        return False

    if not (0 <= data["confidence"] <= 1):
        print("confidence should be between 0 and 1")
        return False

    print("Output is correct")
    return True
output = analyze_reviews(reviews_main)
parsed_output = safe_parse(output)

if parsed_output:
    print(parsed_output)
    validate_output(parsed_output)
else:
    print("Model returned invalid JSON. Try again.")

"""**Test Cases - Evaluation**"""

tc1 = ["Excellent product", "Very happy", "Fast delivery"]   # Positive
tc2 = ["Good but delivery late", "Nice but packaging bad"]   # Mixed
tc3 = ["Very bad product", "Waste of money"]                 # Negative
tc4 = ["Average product", "Okay experience"]                 # Neutral
tc5 = ["Amazing quality", "Loved it"]                        # Positive
tc6 = ["Not good", "Battery bad"]                            # Negative
tc7 = ["Good but expensive"]                                 # Mixed
tc8 = ["I don't know about this product"]                    # Uncertain
tc9 = ["المنتج جيد جدا", "التوصيل متأخر"]                   # Arabic
tc10 = ["Value for money", "Good design", "Slow service"]    # Mixed

test_cases = [tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, tc9, tc10]
expected = ["Positive", "Mixed", "Negative", "Neutral", "Positive", "Negative", "Mixed", "Neutral", "Mixed", "Mixed"]
correct = 0

for i, case in enumerate(test_cases):
    print(f"\nTest Case {i+1}")

    output = analyze_reviews(case)
    parsed = safe_parse(output)

    if parsed:
        is_valid = validate_output(parsed)

        predicted = parsed["sentiment"]
        confidence = parsed["confidence"]

        print("Expected:", expected[i])
        print("Predicted:", predicted)
        print("Confidence:", confidence)

        if predicted == expected[i]:
            correct += 1
    else:
        print("Parsing failed")

print("\nFinal Accuracy:", correct, "/", len(test_cases))

"""**User Interaction with LLM**"""

reviews = []

n = int(input("Enter number of reviews: "))

for i in range(n):
    review = input(f"Enter review {i+1}: ")
    reviews.append(review)

output = analyze_reviews(reviews)

import json
parsed_output = json.loads(output)

print(parsed_output)
validate_output(parsed_output)





























tc1 = ["Excellent product", "Very happy", "Fast delivery"]
tc2 = ["Good but delivery late", "Nice but packaging bad"]
tc3 = ["Very bad product", "Waste of money"]

test_cases = [tc1, tc2, tc3]
expected = ["Positive", "Mixed", "Negative"]

for i, case in enumerate(test_cases):
    print(f"\nTest Case {i+1}")

    output = analyze_reviews(case)
    parsed_output = json.loads(output)

    predicted = parsed_output["sentiment"]

    print(f"Expected: {expected[i]}")
    print(f"Predicted: {predicted}")